<?php

/**
 * The plugin bootstrap file
 *
 * This file is read by WordPress to generate the plugin information in the plugin
 * admin area. This file also includes all of the dependencies used by the plugin,
 * registers the activation and deactivation functions, and defines a function
 * that starts the plugin.
 *
 * @link              http://www.tropotek.com/
 * @since             1.0.0
 * @package           Tk_Listing_Importer
 *
 * @wordpress-plugin
 * Plugin Name:       Tk Listing Importer
 * Plugin URI:        https://github.com/tropotek/tk-listing-importer
 * Description:       Use this plugin to import Listings from remote sites
 * Version:           1.0.0
 * Author:            Mick Mifsud
 * Author URI:        http://www.tropotek.com/
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain:       tk-listing-importer
 * Domain Path:       /languages
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Currently plugin version.
 * Start at version 1.0.0 and use SemVer - https://semver.org
 * Rename this for your plugin and update it as you release new versions.
 */
define( 'TK_LISTING_IMPORTER_VERSION', '1.0.0' );
define( 'TK_LISTING_IMPORTER_URL_KEY', 'R2YFZ+#%E26v3-@mUj1_@P2Edj_3hkaa8j+k*Wd|K4wDZ|27L4cXoLlg]WoSONuW');
define( 'TK_LISTING_IMPORTER_NAME', 'tk-listing-importer' );

if (!session_id() && !headers_sent())
	session_start();


/**
 * @param string|mixed $msg
 */
function tkvd($msg)
{
    if (is_array($msg) || is_object($msg)) $msg = print_r($msg, true);
    if (WP_DEBUG)
        error_log($msg);

}


/**
 * The code that runs during plugin activation.
 * This action is documented in includes/class-tk-listing-importer-activator.php
 */
function activate_tk_listing_importer() {
	require_once plugin_dir_path( __FILE__ ) . 'includes/class-tk-listing-importer-activator.php';
	Tk_Listing_Importer_Activator::activate(TK_LISTING_IMPORTER_NAME);
}

/**
 * The code that runs during plugin deactivation.
 * This action is documented in includes/class-tk-listing-importer-deactivator.php
 */
function deactivate_tk_listing_importer() {
	require_once plugin_dir_path( __FILE__ ) . 'includes/class-tk-listing-importer-deactivator.php';
	Tk_Listing_Importer_Deactivator::deactivate(TK_LISTING_IMPORTER_NAME);
}

register_activation_hook( __FILE__, 'activate_tk_listing_importer' );
register_deactivation_hook( __FILE__, 'deactivate_tk_listing_importer' );



/**
 * The core plugin class that is used to define internationalization,
 * admin-specific hooks, and public-facing site hooks.
 */
require plugin_dir_path( __FILE__ ) . 'includes/class-tk-listing-importer.php';

// HACK: this was added to avoid the errors generated by the ImageMagic graphic lib.
function change_graphic_lib($array) {
	return array( 'WP_Image_Editor_GD', );
}
add_filter( 'wp_image_editors', 'change_graphic_lib' );


/**
 * Begins execution of the plugin.
 *
 * Since everything within the plugin is registered via hooks,
 * then kicking off the plugin from this point in the file does
 * not affect the page life cycle.
 *
 * @since    1.0.0
 */
function run_tk_listing_importer() {

	$plugin = new Tk_Listing_Importer();
	$plugin->run();

}
run_tk_listing_importer();

